[package]
name = "lazy"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.161"
command-group = "5.0.1"

[profile.release]
opt-level = "s"

